import permutation
import random
import numpy as np

def make_data_file(data, output_file, label_file):
    """
    Makes a file for ML_test_auto.py to run ML test on
    """

    print("making file")

    #create files
    output_f = open(output_file, "x")
    output_f = open(output_file, "a")

    label_f = open(label_file, "x")
    label_f = open(label_file, "a")

    num_seq = len(data[0][0])
    seq_len = len(data[0][0][0])

    for datapoint in data:
        sequences = datapoint[0]
        label = datapoint[1]

        output_f.write(str(num_seq) + " " + str(seq_len) + "\n")
        for i, sequence in enumerate(sequences, 1):
            output_f.write("taxon" + str(i) + " " + sequence + "\n")

        label_f.write(str(label) + "\n")


OUTPUT_FILE = "ML_run_file.dat"
LABEL_FILE = "labels.txt"

datapoint = [['GCCCTTTTGAGCATGACCGGCATTAGGCGTGCGGTGCGCTATATCTCGGACAATACTGGTCGTTTAGTGGCGGTCAGCGAGCTATTTCTATCACGACACACCTACGGACCCCAGCGACGGTTTCGGAAGGAAGCAATCATGACTACCTAAAGTAGTTCCAACCCTTCGGCGATGCATTTTGCACGTATTGCCGGGGGAGC',
            'GCCGTTATGAGCATGACCGCCATTAGGCGTATGTTGAGCTATCTGTCGGACAATAGTGGTCGTGTAGTTGCGTTAAGCGAGCTCTGTCGATCACGATCCACCTACGGACGCGAGCGACGGTTTCGAAACGTAGCAAGCATGCCCGCCTAAAATAGTGACAACCCTTCGGCGGAGCGGTTCGCACGTGTCGCGGGGTAAGC',
            'CTCCTTTGGAGCCTGACCGGCATTTGGTTTGTGGTGCGCTATCGCTCGGACACTATTGGCCGTGTAGTCGCGGTCTGGGCGCACTTTCTATCCCGGTTCACCTACGGACGTTAGCGACGGTTTCGAAACCAAGCAAGCATGACCGCCTAAAGACGTACCAACCCTTCCGCGGAGCGGCTTGCACATGTCGCGGCGGGAGC',
            'CTCCTTTTGAGCATGACCGGGAGTAGGCGTGTGGTGCGCTATCGCTCGGGCAATATTGGCCGTTTAGTCGCGGTCTGGGAGCACTTTAAATCACGATTAACCTACGGACGTTCGCGAGGGTTTGGAAACCTAGCTAGCAAGACCGCCTTAAGACGTAATAACCCTTCCGCGGAGCGGCCTGCACATGTCGCGGCGGGAGC'], 1]


# [['TAACTTCTAAGCATCCGTAGGGTCTACACAGGGTTCCTTCTGATCTTAAAACTCTGTAGCGCCCGGACAGGTGTTCGCACTATAATTTCGTCCTCATCCGAAAGCTTCAACTTTGACCTTGAGTTATCTACCTCACCATTTTTTAATTTATACCTATACCATGCTACTGAGCTAATGCAAACAGTAGGGCGTAGTTCAAG',
#     'CAACATCTATCCATTCGTAGGATCTACACAGGGTTTCTTCTGATCTTAAAACTCTGAAGCGCCCATCTAGGTGGGGGCACGATAATCTGGTCCTCATACGAAAGCTTCAACTTTCAACTTGAGTTATCCCGCTCAACCTTCTTTAATTCATACCTTTACCACGCTAAAGAACTAATGCAAGCAGGAGGGCGTAATGGAAG',
#     'TAACTTCTATGCACCGATACGGGCTGCACGGGGTACCTTCTCATCTTAAACCTCTGAGGTTCCCGTCCAGGGGATAGAATCATAATTTCGGACTCATCAGCTTTCTTCTACTTTGATCTGGTACAATCACGCTCAACCCTGGTTAATGTCTACGTCTGCCACGGTTCTGGCCAAGCGTAAGCATACGGCCGTTATGTCAG',
#     'TAACTCCTATGCACTGATAGGGACTACACGGGCTCCCTGTTGATCTTAAAACTCTGAGGTTCCAGGCGAGGTGATAGCAACATAATCTCGTACTCATCCGATTGCTTGAACTTTGATATGGTAGTATCACGCCCAACCCTCTTTAATATCTACCTATGCCAGGGTACTGGCCAAGCGTAATCAGACGGCCGTTATGGCAG'], 0]


data = permutation.transform(datapoint)
print(data)
make_data_file(data, OUTPUT_FILE, LABEL_FILE)
